### ISSUE TITLE
Chaos Guardians despawning or double spawning

### ISSUE THREAD

**Issue by nematrec** [brandon3055/Draconic-Evolution#684]
Chaos guardians either spawn in pairs and work fine otherwise, or spawn singular and will permanently despawn (conditions not certain, haven't gotten one to stay long enough to break all the iron+slab cages)

Additionally guardians despawned in previous versions don't respawn, despite the chaos crystal still existing (and being shielded)

DE Version: 2.0.9.192
Pack: Direwofl20 1.10 pack with certain mods manually updated (including DE)
This is on a server.

**Comment by nematrec** [comment]
Addendum: Singular Guardian seem to despawn after a some amount of time. 

I just fought one, and it straight up disappeared while I was looking at it. It was definitely not outside chunk loading range.

**Comment by brandon3055** [comment]
Ok.. .What? I though i fixed this... This must be some kind of interaction with another mod. Does anything get printed to the console when it vanishes?

**Comment by nematrec** [comment]
05.04 23:55:52 [Server] Server thread/WARN Tried to add entity draconicevolution.ChaosGuardian but it was marked as removed already 
05.04 23:55:52 [Server] Server thread/WARN Wrong location! (622, -4377) should be (625, -4375), EntityChaosGuardian['Chaos Guardian'/143991, l='world', x=9964.41, y=138.37, z=-70022.57] 
05.04 23:55:39 [Server] Server thread/WARN Keeping entity Enderman that already exists with UUID 0440b781-4ffe-4b2c-bddb-920f577376ac

**Comment by Jemsuper** [comment]
Can confirm both of the same problems still happening. ATM:Expert 1.033B multiplayer. DE version 193 latest

**Comment by jarquafelmu** [comment]
Can confirm, I'm having the dragon despawn on me. We had it happen twice in a row. I'm running a FTB Beyond server.

```
21:27:55  [Warn] Wrong location! (-2, -627) should be (0, -625), EntityChaosGuardian['Chaos Guardian'/980337, l='world', x=-30.87, y=154.95, z=-10017.42]
21:27:55  [Warn] Tried to add entity draconicevolution.ChaosGuardian but it was marked as removed already
```
```
22:08:12  [Warn] Wrong location! (-4, 626) should be (0, 625), EntityChaosGuardian['Chaos Guardian'/1453447, l='world', x=-54.12, y=133.53, z=10021.99]
22:08:12  [Warn] Tried to add entity draconicevolution.ChaosGuardian but it was marked as removed already
```

Specs:
Minecraft: 1.10.2
Forge: 12.18.3.2254
FTB Beyond 1.5.3. 
DE 1.10.2-2.0.10.193-universal

**Comment by nematrec** [comment]
Managed to fight a singular one to its death in 193. Confirms that it's not guaranteed/reliable for it to despawn.

**Comment by cracker54** [comment]
I am getting the same error on FTB Beyond 1.5.3. DE  verson: 1.10.2-2.0.10.193 (2.0.10)
[01:02:51] [Server thread/WARN]: Wrong location! (625, -622) should be (625, -625), EntityChaosGuardian['Chaos Guardian'/11315552, l='world', x=10011.50, y=183.20, z=-9948.29]
[01:02:51] [Server thread/WARN]: Tried to add entity draconicevolution.ChaosGuardian but it was marked as removed already

**Comment by Meryl** [comment]
When a duplicate appears, I also get this in the log:

`[07:39:13] [Server thread/WARN]: Keeping entity draconicevolution.ChaosGuardian that already exists with UUID ab38d482-ac4d-4934-8be7-44816378d009`

When killing one of the two Chaos Guardians that appeared at the same time, one of them created one of those "Whoever is screwing with the dragon you need to fix your shit!!" exceptions, and I'm 90% sure it was actually the one I was fighting from the start, which I guess is likely to be the duplicate since it usually takes a few seconds before I can actually see the Chaos Guardian.

**Comment by Ghan04** [comment]
Playing on a server running Direwolf20 1.10 pack and this happened to me three times. Two times it was the dragon vanishing, and one time it was doubling. Just had the third instance happen where it vanished mid-fight. I did get this from my server's log if it helps:

[20:43:58] [Server thread/WARN]: Wrong location! (-626, -9) should be (-625, 0), EntityChaosGuardian['Chaos Guardian'/4313001, l='world', x=-10004.95, y=265.91, z=-134.23]
[20:43:58] [Server thread/WARN]: Tried to add entity draconicevolution.ChaosGuardian but it was marked as removed already

The pack is only on DE version 2.0.10.199 for the latest non-beta release (maybe should be 2.0.10.194?) so not the latest I see here.

**Comment by Hikyuuri** [comment]
I also have this happening, but I have not been watching the log files.  I am using the FTB launcher to launch FTB Beyond 1.5.3 (not which specific version of Draconic Evolution).  The only thing I have changed is I added DynMap to the server for mapping purposes, and made a few config changes in other mods (elevator distances, number of chunks I can load, stuff like that), but nothing to Draconic Evolution.

The first island I went to, I didn't know what I was doing (first time killing a chaos dragon), so I ended up teleporting home using an Advanced Dislocater.  Once I got my bearings and figured out what I was doing wrong, I flew back to the island, but there was no dragon any more.  Flew around the island to see if he happened to just leave the area, no luck.  When I came back to the center of the island, the animation of lightning hitting the spires and blowing them up was happening, to all but 3 of the spires.  The crystal was still shielded.

I decided to immediately fly to a second island, and thinking the TP is what made it break, I stayed this time.  Was flying around, breaking the spires, then suddenly noticed the healthbar disappear, and the "fog" that appears with the dragon vanished.  I didn't stop moving, but I started looking around, and sure enough I couldn't find the dragon.  This time the spires did not blow up, and there were even some spires that I had not made it to yet to break.  I flew around, broke them, nothing changed.  I TP'd away, then back, no difference.

I am going to start recording my Minecraft gameplay, so when it happens next I can either post the video, or at least review it to get some decent screenshots.  I might even try to have the server console in the video feed also, just so they are in sync.  Gotta love NVidia's built in recording feature in the newer gen GPUs.

**Comment by covers1624** [comment]
I'm pretty sure this has been fixed in a recent version of DE, try manually updating it and see if it continues.

**Comment by FluxAdept** [comment]
I am currently playing on a server version of Infinity Lite 1.10, We are currently updated to version 1.8. I have now consecutively gone and fought 2 separate chaos guardians both of which double spawned. This time I actually died cause of lag lol. But, with all this being said, I managed to pull the Console log from immediately after the fight. Here it is. 
[Chaos Error log.txt](https://github.com/brandon3055/Draconic-Evolution/files/1057228/Chaos.Error.log.txt)
Hope this is Helpful Brandon, as I love this mod.

**Comment by brandon3055** [comment]
What DE version is the pack running? To find out go to Mod Options (Next to the regular options button) and get the version. Or just open the mods folder and check the jar version. 

This **IS** Fixed in the latest version.... Unless this is a new issue... I hope not...

**Comment by sloppysailor** [comment]
Just downloaded the new version along with the latest version of brandon and chickenlib .... still have two chaos guardians chasing me around at all times.... very..... very.... frustrating

**Comment by FluxAdept** [comment]
I just looked in my mods folder which is the same as the one on the server and this is the name of the .jar file Draconic-Evolution-1.10.2-2.0.9.192-universal.

**Comment by brandon3055** [comment]
@sloppysailor Is that a new island? because the update wont remove duplicate guardians that already exist.
@FluxAdept Its not fixed in that version, Its fixed in 2.0.12.222

**Comment by sloppysailor** [comment]
Brandon, haven't had a chance to venture to a new island. I'll keep you
posted if anything is out of the ordinary

**Comment by FluxAdept** [comment]
so because the server I run is up to date on the modpack version, how do I go about fixing this? can I update the .jar on the server and itll be okay? or will that bring back mod rejections for clients due to them not having the updated version of DE on clientside?

**Comment by Tahakk** [comment]
You will need to update mod server-sided and anyone that will need to connect will get notification hat they need to update their DE. So to answer your question: Yes I believe that client update will be needed, but if you are running using Twitch Client it is basically matter of few clicks :)
